Player class task7
mariuszlisowski-cs2021/object-oriented-programming pull request #19
Opened 2021-06-17 14:12 UTC by BarTes8

2021-06-17 14:18 UTC, MoreThanADC commented on shm/inc/Player.hpp
> +#include "Ship.hpp"
Do relative path like "shm/inc/Cargo.hpp"  etc.

2021-06-17 14:18 UTC, MoreThanADC commented on shm/inc/Ship.hpp
> +#include "../inc/Cargo.hpp"
Do relative path like "shm/inc/Cargo.hpp"

2021-06-17 14:18 UTC, MoreThanADC commented on shm/main.cpp
> +#include "inc/Player.hpp"
Do relative path

2021-06-18 12:10 UTC, lukasz-kukulka approved these changes

2021-06-18 12:10 UTC, lukasz-kukulka commented on shm/src/Player.cpp
> +    {}
Every argument from initialization list in new line will be more clear

2021-06-18 13:30 UTC, mariuszlisowski approved these changes

2021-06-18 16:48 UTC, mariuszlisowski requested changes

2021-06-18 16:48 UTC, mariuszlisowski commented on shm/src/Player.cpp
>  Player::Player(std::shared_ptr<Ship> ship, size_t money, size_t availableSpace)
unique_ptr

2021-06-18 18:23 UTC, mariuszlisowski requested changes

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/src/Player.cpp
> +#include "inc/Player.hpp"
"shm/inc/Player.hpp"

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/src/Cargo.cpp
> +#include "inc/Cargo.hpp"
"shm/inc/Cargo.hpp"

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/inc/Player.hpp
> +#include "inc/Ship.hpp"
"shm/inc/Cargo.hpp"
"shm/inc/Ship.hpp"

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/inc/Ship.hpp
> +#include "inc/Cargo.hpp"
"shm/inc/Cargo.hpp"

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/inc/Player.hpp
> +#include "inc/Cargo.hpp"
Line

2021-06-18 18:23 UTC, mariuszlisowski commented on shm/src/Ship.cpp
> +#include "inc/Ship.hpp"
"shm/inc/Ship.hpp"

2021-06-19 07:01 UTC, mariuszlisowski requested changes

2021-06-19 07:01 UTC, mariuszlisowski commented on shm/inc/Ship.hpp
>      size_t getSpeed() const { return speed_; };
return int

2021-06-19 07:01 UTC, mariuszlisowski commented on shm/src/Player.cpp
> +    size_t usedSpace = std::accumulate(ship_->getVectorCargo().cbegin(), ship_->getVectorCargo().cend(), 0);
Iteration through a vector of shared pointers but int type needed to add up (amount of cargo).
Thus error: invalid operands to binary expression ('int' and 'const std::__1::shared_ptr<Cargo>')
Hint: each vector element contains a cargo which needs to be accessed.

std::accumulate returns int type but size_t used (which is good) - make accumulate to return size_t

2021-06-19 12:40 UTC, mariuszlisowski requested changes

2021-06-19 12:40 UTC, mariuszlisowski commented on shm/src/Player.cpp
> +        [&usedSpace](const auto& ptrCargo){ usedSpace += *ptrCargo; });
Dosen't make sense because usedSpade is size_t type but *ptrCargo i Cargo type - cannot be added.

2021-06-20 18:24 UTC, mariuszlisowski requested changes

2021-06-20 18:24 UTC, mariuszlisowski commented on shm/src/Player.cpp
> +                    });
return available space

2021-06-20 18:24 UTC, mariuszlisowski commented on shm/src/Ship.cpp
>  Ship::Ship(size_t id, const std::string& name, size_t speed, size_t maxCrew, size_t capacity)
int id

2021-06-20 18:24 UTC, mariuszlisowski commented on shm/inc/Ship.hpp
>      Ship& operator+=(const size_t);
Ship(int, const std::string&, size_t, size_t, size_t);

2021-06-20 18:38 UTC, mariuszlisowski approved these changes

2021-06-20 18:45 UTC, merged