added Alcohol class
mariuszlisowski-cs2021/object-oriented-programming pull request #47
Opened 2021-06-30 12:34 UTC by BarTes8

2021-06-30 14:39 UTC, BarTes8 commented
.

2021-06-30 17:41 UTC, MoreThanADC commented on shm/inc/Alcohol.hpp
> +    size_t getBestPrice() const override { return basePrice_; }
Change getBestPrice to getBasePrice xD

2021-06-30 17:43 UTC, MoreThanADC commented on shm/inc/Alcohol.hpp
> +    size_t getPrice() const override; { return basePrice_ * percentage_ / 96; }
Delete ";" after override

2021-06-30 17:48 UTC, MoreThanADC commented on shm/inc/Alcohol.hpp
> +
Add a comment after which class you are overwriting

2021-06-30 17:48 UTC, MoreThanADC commented on shm/inc/Alcohol.hpp
> +};
add space after last line (enter)

2021-06-30 17:49 UTC, MoreThanADC commented on shm/CMakeLists.txt
>      ${SOURCE_DIR}/Cargo.cpp
delete Cargo.cpp,  this file no longer exists

2021-06-30 17:50 UTC, MoreThanADC requested changes
Fix a few little things

2021-07-01 12:29 UTC, mariuszlisowski requested changes

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/inc/Alcohol.hpp
> +    Alcohol(const std::string&, size_t, size_t, size_t);
variable names

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/inc/Alcohol.hpp
> +    size_t percentage_;
const?

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/inc/Alcohol.hpp
> +    size_t getPrice() const override { return basePrice_ * percentage_ / 96; }
magic number

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/inc/Alcohol.hpp
> +constexpr size_t basePrice = 96;
not MAX_PERCENTAGE instead?

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/inc/Alcohol.hpp
> +    void setBasePrice(size_t basePrice) { basePrice_ = basePrice; }
YAGNI (You Aren't Gonna Need It) - basePrice is already set in a constructor.

2021-07-01 12:29 UTC, mariuszlisowski commented on shm/src/Alcohol.cpp
> +Alcohol::~Alcohol() override = default;
keyword 'override' not allowed here

2021-07-05 20:28 UTC, closed without merging