Task prework 7 done
mariuszlisowski-cs2021/object-oriented-programming pull request #55
Opened 2021-07-03 08:58 UTC by lukasz-kukulka

2021-07-03 10:45 UTC, MoreThanADC approved these changes
Code looks well ;)

2021-07-06 10:11 UTC, mariuszlisowski requested changes

2021-07-06 10:11 UTC, mariuszlisowski commented on shm/src/DryFruit.cpp
> +        rottenDryFruit_ = 10;
Magic number

2021-07-06 10:11 UTC, mariuszlisowski commented on shm/src/DryFruit.cpp
> +    return basePrice_ * (rottenTime_ / 10) * multiplierDryFruit_;
Magic number

2021-07-06 14:08 UTC, closed without merging